name: React Testing

on:
  push:
    branches: 
      - 'main'
      - 'development'
jobs:
  build:
    name: React Unit Test and Integration Test
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: ğŸ‘‹ğŸ» Setup Repository
      uses: actions/checkout@v3

    - name: ğŸ“¦ Clean & Install Dependencies
      run: npm ci

    - name: âš¡ï¸ Run Tests
      run: npm run test