name: React Testing

on:
  push:
    branches: 
      - 'main'
      - 'develop'
      - 'feature/**'
      - 'hotfix/**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: ğŸ‘‹ğŸ» Setup Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: ğŸ“— Use Node.JS
      uses: actions/setup-node@v3
    
    - name: ğŸ‘® Lint Code Base
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_JAVASCRIPT_ES: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: ğŸ“¦ Clean & Install Dependencies
      run: npm ci

    - name: âš’ Build App
      run: npm run build --if-present

    - name: âš¡ï¸ Run Tests
      run: npm run test